# Generated by Django 4.2.6 on 2023-10-30 02:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appoint_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="Date of appointment")),
                ("time", models.TimeField(verbose_name="Time of appointment")),
                (
                    "symptoms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Heart and Cardiovascular", "Heart and Cardiovascular"),
                            (
                                "skin, hair, nails, and mucous membranes",
                                "skin, hair, nails, and mucous membranes",
                            ),
                            (
                                "life-threatening medical conditions",
                                "life-threatening medical conditions",
                            ),
                            (
                                "allergies and immunological disorder",
                                "allergies and immunological disorder",
                            ),
                            ("anesthesia", "anesthesia "),
                            ("colon,rectum,and anus", "colon,rectum,and anus"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "symptoms",
                    models.CharField(
                        choices=[
                            ("Heart and Cardiovascular", "Heart and Cardiovascular"),
                            (
                                "skin, hair, nails, and mucous membranes",
                                "skin, hair, nails, and mucous membranes",
                            ),
                            (
                                "life-threatening medical conditions",
                                "life-threatening medical conditions",
                            ),
                            (
                                "allergies and immunological disorder",
                                "allergies and immunological disorder",
                            ),
                            ("anesthesia", "anesthesia "),
                            ("colon,rectum,and anus", "colon,rectum,and anus"),
                        ],
                        default=None,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialisation",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologists", "Dermatologists"),
                            (
                                "Emergency Medicine Specialists",
                                "Emergency Medicine Specialists",
                            ),
                            ("Allergists/Immunologists", "Allergists/Immunologists"),
                            ("Anesthesiologists", "Anesthesiologists"),
                            ("Colon and Rectal Surgeons", "Colon and Rectal Surgeons"),
                        ],
                        default=None,
                        max_length=50,
                        verbose_name="Specialization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("did", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dname",
                    models.CharField(
                        default=None, max_length=100, verbose_name="Doctor Name"
                    ),
                ),
                (
                    "specialisation",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologists", "Dermatologists"),
                            (
                                "Emergency Medicine Specialists",
                                "Emergency Medicine Specialists",
                            ),
                            ("Allergists/Immunologists", "Allergists/Immunologists"),
                            ("Anesthesiologists", "Anesthesiologists"),
                            ("Colon and Rectal Surgeons", "Colon and Rectal Surgeons"),
                        ],
                        default=None,
                        max_length=50,
                        verbose_name="Specialization",
                    ),
                ),
                (
                    "no_of_patients",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(5)],
                        verbose_name="No. of Patients",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=30, verbose_name="First Name")),
                (
                    "middlename",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Middle Name"
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Last Name"
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="Date of Birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("O", "Other")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("apstatus", models.BooleanField(default=False)),
                (
                    "did",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.doctor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctors_Detail",
            fields=[
                (
                    "did",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="administrator.doctor",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=30, null=True)),
                ("address", models.TextField(blank=True, max_length=50, null=True)),
                ("contact_no", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Patients_Detail",
            fields=[
                (
                    "contact_no",
                    models.CharField(
                        default=None, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("address", models.TextField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=30, null=True)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        default="B+",
                        max_length=3,
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                ("report_no", models.BigAutoField(primary_key=True, serialize=False)),
                ("sample_date", models.DateField(verbose_name="Sample Date")),
                ("amount", models.IntegerField(default=0, verbose_name="Amount")),
                (
                    "phlev",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Ph level",
                    ),
                ),
                (
                    "chlolev",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Cholesterol level",
                    ),
                ),
                (
                    "sucrlev",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Sucrose level",
                    ),
                ),
                ("wbcratio", models.IntegerField(default=0, verbose_name="WBC ratio")),
                ("rbcratio", models.IntegerField(default=0, verbose_name="RBC ratio")),
                (
                    "reports",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Reports"
                    ),
                ),
                (
                    "appoint_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.appointment",
                    ),
                ),
                (
                    "did",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.doctor",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "bill_no",
                    models.BigAutoField(
                        default=None, primary_key=True, serialize=False
                    ),
                ),
                (
                    "room_charges",
                    models.IntegerField(default=0, verbose_name="Room Charges"),
                ),
                (
                    "operation_charges",
                    models.IntegerField(default=0, verbose_name="Operation Charges"),
                ),
                (
                    "doctor_fee",
                    models.IntegerField(default=0, verbose_name="Doctor Fee"),
                ),
                (
                    "no_of_days",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="No Of Days Stayed"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(blank=True, default=0, verbose_name="Amount"),
                ),
                (
                    "total_amount",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Total Amount"
                    ),
                ),
                (
                    "appoint_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.appointment",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.patient",
                    ),
                ),
                (
                    "report_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.labreport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="did",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="pid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.patient",
            ),
        ),
        migrations.CreateModel(
            name="Discharge",
            fields=[
                (
                    "appoint_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="administrator.appointment",
                    ),
                ),
                (
                    "reg_date",
                    models.DateField(blank=True, verbose_name="Registration Date"),
                ),
                (
                    "discharge_date",
                    models.DateField(auto_now=True, verbose_name="Discharge Date"),
                ),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.doctor",
                    ),
                ),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrator.patient",
                    ),
                ),
            ],
        ),
    ]
