# Generated by Django 4.2.6 on 2023-10-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_remove_doctor_user_remove_patient_user_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
