# Generated by Django 4.2.6 on 2023-10-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_alter_patient_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="appointment",
            table="Appointment",
        ),
        migrations.AlterModelTable(
            name="bill",
            table="Bill",
        ),
        migrations.AlterModelTable(
            name="condition",
            table="Condition",
        ),
        migrations.AlterModelTable(
            name="discharge",
            table="Discharge",
        ),
        migrations.AlterModelTable(
            name="doctor",
            table="Doctor",
        ),
        migrations.AlterModelTable(
            name="doctors_detail",
            table="Doctors_Detail",
        ),
        migrations.AlterModelTable(
            name="labreport",
            table="LabReport",
        ),
        migrations.AlterModelTable(
            name="patients_detail",
            table="Patients_Detail",
        ),
    ]
