# Generated by Django 4.2.6 on 2023-10-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0005_alter_appointment_table_alter_bill_table_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Condition",
            new_name="Conditions",
        ),
        migrations.AlterModelTable(
            name="conditions",
            table="Conditions",
        ),
    ]
