# Generated by Django 4.2.6 on 2023-10-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0008_rename_appoint_id_labreport_appoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discharge",
            old_name="appoint_id",
            new_name="appoint",
        ),
    ]
