# Generated by Django 4.2.6 on 2023-10-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0009_rename_appoint_id_discharge_appoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="appoint",
            new_name="appoint_id",
        ),
        migrations.RenameField(
            model_name="discharge",
            old_name="appoint",
            new_name="appoint_id",
        ),
        migrations.RenameField(
            model_name="labreport",
            old_name="appoint",
            new_name="appoint_id",
        ),
    ]
