# Generated by Django 4.2.6 on 2023-11-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0012_labreport_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="no_of_patients",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="status",
        ),
    ]
