# Generated by Django 4.2.6 on 2023-11-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0013_remove_doctor_no_of_patients_remove_doctor_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
