# Generated by Django 4.2.6 on 2023-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0014_appointment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="status",
            new_name="dstatus",
        ),
        migrations.AddField(
            model_name="appointment",
            name="lstatus",
            field=models.BooleanField(default=False),
        ),
    ]
