# Generated by Django 4.2.6 on 2023-11-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0015_rename_status_appointment_dstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors_detail",
            name="email",
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
